<a href="https://colab.research.google.com/github/FredArgoX/ChaoticTest_Numpy/blob/main/01_NumPy_quickstart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Source: [NumPy Quickstart](https://numpy.org/doc/stable/user/quickstart.html)

# The basics

NumPy's main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.

Fo example, the array for the coordinates of a point in 3D space, `[1, 2, 1]`, has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3

In [ ]:
[[1., 0., 0.],
 [0., 1., 2.]]

NumPy's array class is called `ndarray`. It is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an `ndarray` object are:

- `ndarray.ndim`: the number of axes (dimensions) of the array.

- `ndarray.shape`: the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with *n* rows and *m* columns, `shape` will be `(n,m)`. The length of the `shape` tuple is therefore the number of axes, `ndim`.

- `ndarray.size`: the total number of elements of the array. This is equal to the product of the elements of `shape`.

- `ndarray.dtype`: an object describing the type of the elements in the array. One can create or specify dtype's using standard Python types. Additionaly NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

- `ndarray.itemsize`: the size in bytes of each element of the array. For example, an array of elements of type `float64` has `itemsize` 8 (=64/8), while one of type `complex32` has `itemsize` 4 (=32/8). It is equivalent to `ndarray.dtype.itemsize`.

- `ndarray.data`: the buffer containing the actual elemenets of the array. Normally, we won't need to use this attribute because we will access the elements in an array using indexing facilities.

### An example

In [1]:
import numpy as np

a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.ndim

2

In [3]:
a.shape

(3, 5)

In [4]:
a.size

15

In [5]:
a.dtype

dtype('int64')

In [8]:
a.dtype.name

'int64'

In [6]:
a.itemsize

8

In [7]:
a.data

In [9]:
type(a)

numpy.ndarray

In [10]:
b = np.array([6, 7, 8])
type(b)

numpy.ndarray

In [11]:
b.dtype.name

'int64'

### Array creation

There are several ways to create arrays.

For example, you can create an array from a regular Pyhton list or tuple using the `array` function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [12]:
import numpy as np

a = np.array([2, 3, 4])
b = np.array([1.2, 3.5, 5.1])

In [13]:
a.dtype

dtype('int64')

In [14]:
b.dtype

dtype('float64')

A frequent error consists in calling `array` with multiple arguments, rather than providing a single sequence as an argument.

In [15]:
a = np.array(1, 2, 3, 4) # WRONG

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [16]:
a = np.array([1, 2, 3, 4]) # RIGHT

`array` transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [17]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
b.dtype.name

'float64'

The type of the array can also be explicitly specified at creation time:

In [19]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Often, the elemnts

### Printing arrays

### Basic operations

### Universal functions

### Indexing, slicing and iterating

# Shape manipulation

### Changing the shape of an array

### Stacking together different arrays

### Splitting one aray into several smaller ones

# Copies and views

### No copy at all

### View or shallow copy

### Deep copy

### Functions and methods overview

# Less basic

### Broadcasting rules

# Advanced indexing and index tricks

### Indexing with arrays of indices

### Indexing with boolean arrays

### The ix_() function

### Indexing with strings

# Tricks and tips

### Automatic reshaping

### Vector stacking

### Histograms